#!/bin/sh

cat << __here__ > runtests
#!/bin/sh

LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:.
export LD_LIBRARY_PATH

echo "It may take a while for the tests to complete"

for i in $*
do
	./\$i
done >mptest.log 2>&1

echo "Test results:"
cat mptest.log
__here__

chmod 755 runtests

exit 0

